version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  prometheus:
    image: prom/prometheus:v2.47.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 9090:9090
    networks:
      - iris

  node-exporter:
    image: prom/node-exporter:v1.6.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./textfile:/etc/textfile
    expose:
      - "9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.mdadm'
      - '--no-collector.nfs'
      - '--no-collector.nfsd'
      - '--no-collector.xfs'
      - '--no-collector.zfs'
      - '--collector.textfile.directory=/etc/textfile'
    networks:
      - iris
    healthcheck:
      test: sed -E -i "s/[0-9]+/$$RANDOM/" /etc/textfile/random.prom
      interval: 3s
      timeout: 1s
      retries: 1
      start_period: 5s

networks:
  iris:
    name: iris
