---
scrape_configs:
  - job_name: scrape-containers
    docker_sd_configs:
      - host: "unix:///host/var/run/docker.sock"
        refresh_interval: 10s

  - job_name: "blackbox"
    scheme: http
    params:
      module:
        - http_2xx
        - tcp_connect
        - icmp
    docker_sd_configs:
      - host: "unix:///host/var/run/docker.sock"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
